Name:           ros-melodic-bondpy
Version:        1.8.2
Release:        0%{?dist}
Summary:        ROS bondpy package

Group:          Development/Libraries
License:        BSD
URL:            http://www.ros.org/wiki/bondpy
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       libuuid-devel
Requires:       ros-melodic-rospy
Requires:       ros-melodic-smclib
BuildRequires:  ros-melodic-bond
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-rospy
BuildRequires:  ros-melodic-smclib

%description
Python implementation of bond, a mechanism for checking when another process has
terminated.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Fri Apr 27 2018 Mikael Arguedas <mikael@osrfoundation.org> - 1.8.2-0
- Autogenerated by Bloom

* Fri Mar 02 2018 Mikael Arguedas <mikael@osrfoundation.org> - 1.8.1-0
- Autogenerated by Bloom

