%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-bond-core
Version:        1.8.6
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS bond_core package

License:        BSD
URL:            http://www.ros.org/wiki/bond_core
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-noetic-bond
Requires:       ros-noetic-bondcpp
Requires:       ros-noetic-bondpy
Requires:       ros-noetic-smclib
BuildRequires:  ros-noetic-catkin
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
A bond allows two processes, A and B, to know when the other has terminated,
either cleanly or by crashing. The bond remains connected until it is either
broken explicitly or until a heartbeat times out.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Fri Aug 28 2020 Michael Carroll <michael@openrobotics.org> - 1.8.6-1
- Autogenerated by Bloom

* Thu May 21 2020 Michael Carroll <michael@openrobotics.org> - 1.8.5-2
- Autogenerated by Bloom

* Thu May 14 2020 Michael Carroll <michael@openrobotics.org> - 1.8.5-1
- Autogenerated by Bloom

* Mon Feb 24 2020 Michael Carroll <michael@openrobotics.org> - 1.8.4-1
- Autogenerated by Bloom

