Name:           ros-lunar-bondcpp
Version:        1.8.0
Release:        0%{?dist}
Summary:        ROS bondcpp package

Group:          Development/Libraries
License:        BSD
URL:            http://www.ros.org/wiki/bondcpp
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       libuuid-devel
Requires:       ros-lunar-bond
Requires:       ros-lunar-roscpp
Requires:       ros-lunar-smclib
BuildRequires:  boost-devel
BuildRequires:  libuuid-devel
BuildRequires:  ros-lunar-bond
BuildRequires:  ros-lunar-catkin
BuildRequires:  ros-lunar-cmake-modules >= 0.3.2
BuildRequires:  ros-lunar-roscpp
BuildRequires:  ros-lunar-smclib

%description
C++ implementation of bond, a mechanism for checking when another process has
terminated.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Thu Jul 27 2017 Mikael Arguedas <mikael@osrfoundation.org> - 1.8.0-0
- Autogenerated by Bloom

* Mon Mar 27 2017 Mikael Arguedas <mikael@osrfoundation.org> - 1.7.19-0
- Autogenerated by Bloom

* Mon Mar 27 2017 Mikael Arguedas <mikael@osrfoundation.org> - 1.7.18-1
- Autogenerated by Bloom

* Wed Feb 22 2017 Mikael Arguedas <mikael@osrfoundation.org> - 1.7.18-0
- Autogenerated by Bloom

