%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-bondcpp
Version:        1.8.5
Release:        2%{?dist}%{?release_suffix}
Summary:        ROS bondcpp package

License:        BSD
URL:            http://www.ros.org/wiki/bondcpp
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       boost-python3-devel
Requires:       libuuid-devel
Requires:       ros-noetic-bond
Requires:       ros-noetic-roscpp
Requires:       ros-noetic-smclib
BuildRequires:  boost-devel
BuildRequires:  boost-python3-devel
BuildRequires:  libuuid-devel
BuildRequires:  ros-noetic-bond
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-cmake-modules >= 0.3.2
BuildRequires:  ros-noetic-roscpp
BuildRequires:  ros-noetic-smclib
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
C++ implementation of bond, a mechanism for checking when another process has
terminated.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Thu May 21 2020 Michael Carroll <michael@openrobotics.org> - 1.8.5-2
- Autogenerated by Bloom

* Thu May 14 2020 Michael Carroll <michael@openrobotics.org> - 1.8.5-1
- Autogenerated by Bloom

* Mon Feb 24 2020 Michael Carroll <michael@openrobotics.org> - 1.8.4-1
- Autogenerated by Bloom

